name: build
on: push
jobs:
  test-push-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: 'pcov'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --dev

      - name: Run unit test
        run: composer phpunit

      - name: Check coding standard
        run: composer phpcs
